# Generated by Django 6.0 on 2025-12-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'InProgress'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
